import { ResumeData } from "./types";

export const TRANSLATIONS = {
  vi: {
    welcome: "Xin chào! Tôi là **SlothCV** — chuyên gia tư vấn CV của bạn.\n\nTôi sẽ không hỏi bạn điền form. Thay vào đó, chúng ta sẽ trò chuyện để tôi hiểu câu chuyện sự nghiệp của bạn, sau đó tôi mới xây dựng một CV thực sự nổi bật.\n\nĐể bắt đầu: **Bạn đang tìm kiếm vị trí gì, và bạn đang ở giai đoạn nào trong sự nghiệp?**",
    newChat: "Cuộc trò chuyện mới",
    history: "Lịch sử",
    recentChats: "Gần đây",
    placeholder: "Nhập tin nhắn hoặc yêu cầu thay đổi thiết kế...",
    send: "Gửi",
    preview: "Xem trước",
    historyTitle: "Lịch sử Resume",
    language: "Ngôn ngữ",
    noSessions: "Chưa có cuộc trò chuyện nào",
    settings: "Cài đặt",
    darkMode: "Chế độ tối",
    lightMode: "Chế độ sáng",
    save: "Lưu Cài Đặt",
    saving: "Đang lưu...",
    saved: "Đã Lưu!",
    cancel: "Hủy",
    close: "Đóng",
    clearData: "Xóa Dữ Liệu",
    clearDataConfirm: "Bạn có chắc muốn xóa TOÀN BỘ dữ liệu bao gồm lịch sử trò chuyện, resume và thiết lập? Hành động này không thể hoàn tác.",
    clearDataError: "Lỗi khi xóa dữ liệu",
    apiKeyMissing: "Thiếu API Key. Vui lòng cấu hình API Key trong phần cài đặt để tiếp tục sử dụng.",
    openSettings: "Mở Cài Đặt",
    resumeDraft: "Bản nháp Resume",
    artifactDesc: "Bản nháp mới nhất đã được AI tạo/cập nhật.",
    clickToView: "Click để xem",
    open: "Đang mở",
    preparingPdf: "Đang chuẩn bị bản in PDF...",
    pdfOpened: "Đã mở hộp thoại lưu PDF!",
    pdfError: "Lỗi khi chuẩn bị file PDF!",
    profilePhotoAttached: "Ảnh đại diện đã đính kèm",
    noResumeData: "Chưa có dữ liệu Resume.",
    zoomIn: "Phóng to",
    zoomOut: "Thu nhỏ",
    resetZoom: "Về ban đầu",
    toggleSidebar: "Đóng/Mở thanh bên",
    hidePreview: "Ẩn xem trước",
    showPreview: "Hiện xem trước",
    attachPhoto: "Đính kèm ảnh",
    exporting: "Đang xuất...",
    artifactPreview: "XEM TRƯỚC ARTIFACT",
    apiProvider: "Nhà cung cấp API",
    baseUrl: "URL cơ sở",
    apiKey: "Mã khóa API",
    model: "Mô hình",
    fetchModels: "Đang lấy danh sách...",
    noModels: "Không có mô hình nào",
    refresh: "Làm mới",
    apiKeyPlaceholder: "Nhập API key",
    optionalLocal: "(tùy chọn cho local)",
    enterKeyToLoad: "Nhập API key để tải mô hình",
    modelNamePlaceholder: "Tên mô hình (VD: gpt-4o, llama3.2)",
    selectModel: "— Chọn một mô hình —",
    restore: "Khôi phục",
    maximize: "Phóng to",
    minimize: "Thu nhỏ",
    errorLabel: "Lỗi"
  },
  en: {
    welcome: "Hi! I'm **SlothCV** — your personal career consultant.\n\nI won't ask you to fill out a form. Instead, we'll have a real conversation so I can understand your professional story — then I'll craft a resume that actually stands out.\n\nTo get started: **What role are you targeting, and where are you in your career right now?**",
    newChat: "New Chat",
    history: "History",
    recentChats: "Recent Chats",
    placeholder: "Type a message or ask for a design change...",
    send: "Send",
    preview: "Preview",
    historyTitle: "Resume History",
    language: "Language",
    noSessions: "No conversations yet",
    settings: "Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    save: "Save Settings",
    saving: "Saving...",
    saved: "Saved!",
    cancel: "Cancel",
    close: "Close",
    clearData: "Clear All Data",
    clearDataConfirm: "Are you sure you want to delete ALL data including chat history, resumes, and settings? This action cannot be undone.",
    clearDataError: "Error clearing data",
    apiKeyMissing: "API Key missing. Please configure your API Key in settings to continue.",
    openSettings: "Open Settings",
    resumeDraft: "Resume Draft",
    artifactDesc: "The latest draft has been created/updated by AI.",
    clickToView: "Click to view",
    open: "Open",
    preparingPdf: "Preparing PDF for print...",
    pdfOpened: "Print dialog opened!",
    pdfError: "Error preparing PDF!",
    profilePhotoAttached: "Profile photo attached",
    noResumeData: "No Resume data yet.",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    resetZoom: "Reset Zoom",
    toggleSidebar: "Toggle sidebar",
    hidePreview: "Hide preview",
    showPreview: "Show preview",
    attachPhoto: "Attach photo",
    exporting: "Exporting...",
    artifactPreview: "ARTIFACT PREVIEW",
    apiProvider: "API Provider",
    baseUrl: "Base URL",
    apiKey: "API Key",
    model: "Model",
    fetchModels: "Fetching models...",
    noModels: "No models found",
    refresh: "Refresh",
    apiKeyPlaceholder: "Enter API key",
    optionalLocal: "(optional for local)",
    enterKeyToLoad: "Enter API key to load models",
    modelNamePlaceholder: "Model name (e.g. gpt-4o, llama3.2)",
    selectModel: "— Select a model —",
    restore: "Restore",
    maximize: "Maximize",
    minimize: "Minimize",
    errorLabel: "Error"
  },
  fr: {
    welcome: "Bonjour ! Je suis **SlothCV** — votre consultant carrière personnel.\n\nJe ne vous demanderai pas de remplir un formulaire. Nous allons avoir une vraie conversation pour comprendre votre parcours, puis je créerai un CV qui se démarque vraiment.\n\nPour commencer : **Quel poste visez-vous et où en êtes-vous trong votre carrière ?**",
    newChat: "Nouvelle discussion",
    history: "Historique",
    recentChats: "Discussions récentes",
    placeholder: "Tapez un message hoặc demandez un changement de thiết kế...",
    send: "Envoyer",
    preview: "Aperçu",
    historyTitle: "Historique du CV",
    language: "Langue",
    noSessions: "Aucune discussion pour le moment",
    settings: "Paramètres",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    save: "Enregistrer",
    saving: "Enregistrement...",
    saved: "Enregistré !",
    cancel: "Annuler",
    close: "Fermer",
    clearData: "Effacer toutes les données",
    clearDataConfirm: "Voulez-vous vraiment supprimer TOUTES les données ? Cette hành động est irréversible.",
    clearDataError: "Erreur lors de l'effacement",
    apiKeyMissing: "Clé API manquante. Veuillez configurer votre clé dans các paramètres.",
    openSettings: "Ouvrir các paramètres",
    resumeDraft: "Brouillon du CV",
    artifactDesc: "Le dernier brouillon a été créé/mis à jour par l'IA.",
    clickToView: "Cliquer pour voir",
    open: "Ouvert",
    preparingPdf: "Préparation du PDF...",
    pdfOpened: "Boîte de dialogue d'impression ouverte !",
    pdfError: "Erreur lors de la préparation du PDF !",
    profilePhotoAttached: "Photo de profil jointe",
    noResumeData: "Aucune donnée de CV pour le moment.",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    resetZoom: "Réinitialiser le zoom",
    toggleSidebar: "Basculer la barre latérale",
    hidePreview: "Masquer l'aperçu",
    showPreview: "Afficher l'aperçu",
    attachPhoto: "Joindre une photo",
    exporting: "Exportation...",
    apiProvider: "Fournisseur d'API",
    baseUrl: "URL de base",
    apiKey: "Clé API",
    model: "Modèle",
    fetchModels: "Récupération...",
    noModels: "Aucun modèle",
    refresh: "Actualiser",
    apiKeyPlaceholder: "Clé API",
    optionalLocal: "(optionnel pour local)",
    enterKeyToLoad: "Entrez la clé API pour charger les modèles",
    modelNamePlaceholder: "Nom du modèle",
    selectModel: "— Choisir un modèle —",
    restore: "Restaurer",
    maximize: "Maximiser",
    minimize: "Minimiser",
    errorLabel: "Erreur"
  },
  de: {
    welcome: "Hallo! Ich bin **SlothCV** — Ihr persönlicher Karriereberater.\n\nIch werde Sie nicht bitten, ein Formular auszufüllen. Wir führen ein echtes Gespräch, damit ich Ihre berufliche Geschichte verstehe — dann erstelle ich einen Lebenslauf, der wirklich auffällt.\n\nZum Einstieg: **Welche Stelle streben Sie an und wo stehen Sie in Ihrer Karriere?**",
    newChat: "Neuer Chat",
    history: "Verlauf",
    recentChats: "Letzte Chats",
    placeholder: "Geben Sie eine Nachricht ein oder fragen Sie nach einer Designänderung...",
    send: "Senden",
    preview: "Vorschau",
    historyTitle: "Lebenslauf-Verlauf",
    language: "Sprache",
    noSessions: "Noch keine Gespräche",
    settings: "Einstellungen",
    darkMode: "Dunkelmodus",
    lightMode: "Hellmodus",
    save: "Speichern",
    saving: "Speichert...",
    saved: "Gespeichert!",
    cancel: "Abbrechen",
    close: "Schließen",
    clearData: "Alle Daten löschen",
    clearDataConfirm: "Sind Sie sicher, dass Sie ALLE Daten löschen möchten? Dies kann nicht rückgängig gemacht werden.",
    clearDataError: "Fehler beim Löschen",
    apiKeyMissing: "API-Key fehlt. Bitte konfigurieren Sie ihn in các Einstellungen.",
    openSettings: "Einstellungen öffnen",
    resumeDraft: "Lebenslauf-Entwurf",
    artifactDesc: "Der neueste Entwurf wurde von der KI erstellt/aktualisiert.",
    clickToView: "Klicken zum Ansehen",
    open: "Offen",
    preparingPdf: "PDF wird vorbereitet...",
    pdfOpened: "Druckdialog geöffnet!",
    pdfError: "Fehler bei der PDF-Vorbereitung!",
    profilePhotoAttached: "Profilbild angehängt",
    noResumeData: "Noch keine Lebenslauf-Daten.",
    zoomIn: "Vergrößern",
    zoomOut: "Verkleinern",
    resetZoom: "Zoom zurücksetzen",
    toggleSidebar: "Seitenleiste umschalten",
    hidePreview: "Vorschau ausblenden",
    showPreview: "Vorschau anzeigen",
    attachPhoto: "Foto anhängen",
    exporting: "Exportiere...",
    apiProvider: "API-Anbieter",
    baseUrl: "Basis-URL",
    apiKey: "API-Key",
    model: "Modell",
    fetchModels: "Lade Modelle...",
    noModels: "Keine Modelle",
    refresh: "Aktualisieren",
    apiKeyPlaceholder: "API-Key",
    optionalLocal: "(optional für lokal)",
    enterKeyToLoad: "API-Key eingeben, um Modelle zu laden",
    modelNamePlaceholder: "Modellname",
    selectModel: "— Modell auswählen —",
    restore: "Wiederherstellen",
    maximize: "Maximieren",
    minimize: "Minimieren",
    errorLabel: "Fehler"
  },
  ja: {
    welcome: "こんにちは！私は**SlothCV** — あなた専属のキャリアコンサルタントです。\n\nフォームへの記入はお願いしません。代わりに、あなたのキャリアストーリーを理解するための対話を行い、本当に目立つ履歴書を作成します。\n\nまず教えてください：**どんなポジションを目指していますか？現在のキャリア段階は？**",
    newChat: "新しいチャット",
    history: "履歴",
    recentChats: "最近のチャット",
    placeholder: "メッセージを入力するか、デザインの変更を依頼してください...",
    send: "送信",
    preview: "プレビュー",
    historyTitle: "履歴書の履歴",
    language: "言語",
    noSessions: "まだ会話はありません",
    settings: "設定",
    darkMode: "ダークモード",
    lightMode: "ライトモード",
    save: "設定を保存",
    saving: "保存中...",
    saved: "保存完了！",
    cancel: "キャンセル",
    close: "閉じる",
    clearData: "全データを消去",
    clearDataConfirm: "本当に全てのデータを削除しますか？この操作は取り消せません。",
    clearDataError: "消去中にエラーが発生しました",
    apiKeyMissing: "APIキーがありません。設定から構成してください。",
    openSettings: "設定を開く",
    resumeDraft: "履歴書のドラフト",
    artifactDesc: "最新のドラフトがAIによって作成/更新されました。",
    clickToView: "クリックして表示",
    open: "表示中",
    preparingPdf: "PDFを準備中...",
    pdfOpened: "印刷ダイアログが開きました！",
    pdfError: "PDFの準備中にエラーが発生しました！",
    profilePhotoAttached: "プロフィール写真が添付されました",
    noResumeData: "履歴書データがまだありません。",
    zoomIn: "拡大",
    zoomOut: "縮小",
    resetZoom: "ズームをリセット",
    toggleSidebar: "サイドバーの切り替え",
    hidePreview: "プレビューを隠す",
    showPreview: "プレビューを表示",
    attachPhoto: "写真を添付",
    exporting: "書き出し中...",
    apiProvider: "APIプロバイダー",
    baseUrl: "ベースURL",
    apiKey: "APIキー",
    model: "モデル",
    fetchModels: "モデルを取得中...",
    noModels: "モデルが見つかりません",
    refresh: "更新",
    apiKeyPlaceholder: "APIキー",
    optionalLocal: "(ローカルの場合は任意)",
    enterKeyToLoad: "モデルを読み込むためにAPIキーを入力してください",
    modelNamePlaceholder: "モデル名",
    selectModel: "— モデルを選択 —",
    restore: "元に戻す",
    maximize: "最大化",
    minimize: "最小化",
    errorLabel: "エラー"
  },
  ko: {
    welcome: "안녕하세요! 저는 **SlothCV** — 당신의 개인 커리어 컨설턴트입니다.\n\n양식을 작성하라고 하지 않겠습니다. 대신 진짜 대화를 통해 당신의 커리어 스토리를 이해한 후, 정말 눈에 띄는 이력서를 만들어 드리겠습니다.\n\n시작하겠습니다: **어떤 포지션을 목표로 하시나요? 현재 커리어 단계는 어디인가요?**",
    newChat: "새 채팅",
    history: "기록",
    recentChats: "최근 채팅",
    placeholder: "메시지를 입력하거나 디자인 변경을 요청하세요...",
    send: "전송",
    preview: "미리보기",
    historyTitle: "이력서 기록",
    language: "언어",
    noSessions: "아직 대화가 없습니다",
    settings: "설정",
    darkMode: "다크 모드",
    lightMode: "라이트 모드",
    save: "설정 저장",
    saving: "저장 중...",
    saved: "저장됨!",
    cancel: "취소",
    close: "닫기",
    clearData: "모든 데이터 삭제",
    clearDataConfirm: "정말로 모든 데이터를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
    clearDataError: "데이터 삭제 중 오류 발생",
    apiKeyMissing: "API 키가 없습니다. 설정에서 구성해 주세요.",
    openSettings: "설정 열기",
    resumeDraft: "이력서 초안",
    artifactDesc: "AI가 최신 초안을 생성/업데이트했습니다.",
    clickToView: "클릭하여 보기",
    open: "열림",
    preparingPdf: "PDF 인쇄 준비 중...",
    pdfOpened: "인쇄 대화 상자가 열렸습니다!",
    pdfError: "PDF 준비 중 오류 발생!",
    profilePhotoAttached: "프로필 사진이 첨부되었습니다",
    noResumeData: "이력서 데이터가 아직 없습니다.",
    zoomIn: "확대",
    zoomOut: "축소",
    resetZoom: "줌 초기화",
    toggleSidebar: "사이드바 토글",
    hidePreview: "미리보기 숨기기",
    showPreview: "미리보기 표시",
    attachPhoto: "사진 첨부",
    exporting: "내보내는 중...",
    apiProvider: "API 제공업체",
    baseUrl: "기본 URL",
    apiKey: "API 키",
    model: "모델",
    fetchModels: "모델 목록 가져오는 중...",
    noModels: "모델을 찾을 수 없음",
    refresh: "새로고침",
    apiKeyPlaceholder: "API 키",
    optionalLocal: "(로컬의 경우 선택 사항)",
    enterKeyToLoad: "모델을 로드하려면 API 키를 입력하세요",
    modelNamePlaceholder: "모델 이름",
    selectModel: "— 모델 선택 —",
    restore: "이전 크기로",
    maximize: "최대화",
    minimize: "최소화",
    errorLabel: "오류"
  },
  zh: {
    welcome: "你好！我是 **SlothCV** — 您的专属职业顾问。\n\n我不会让您填写表格。我们将进行真实对话，让我了解您的职业故事，然后为您打造一份真正脱颖而出的简历。\n\n首先请告诉我：**您目标的职位是什么？您目前处于职业生涯的哪个阶段？**",
    newChat: "新聊天",
    history: "历史",
    recentChats: "最近聊天",
    placeholder: "输入消息或请求设计更改...",
    send: "发送",
    preview: "预览",
    historyTitle: "简历历史",
    language: "语言",
    noSessions: "暂无对话",
    settings: "设置",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    save: "保存设置",
    saving: "保存中...",
    saved: "已保存！",
    cancel: "取消",
    close: "关闭",
    clearData: "清除所有数据",
    clearDataConfirm: "确定要删除所有数据吗？此操作无法撤销。",
    clearDataError: "清除数据时出错",
    apiKeyMissing: "缺少 API 密钥。请在设置中配置。",
    openSettings: "打开设置",
    resumeDraft: "简历草案",
    artifactDesc: "AI 已创建/更新最新草案。",
    clickToView: "点击查看",
    open: "已打开",
    preparingPdf: "正在准备 PDF 打印...",
    pdfOpened: "打印对话框已打开！",
    pdfError: "准备 PDF 时出错！",
    profilePhotoAttached: "已添加个人照片",
    noResumeData: "暂无简历数据。",
    zoomIn: "放大",
    zoomOut: "缩小",
    resetZoom: "重置缩放",
    toggleSidebar: "切换侧边栏",
    hidePreview: "隐藏预览",
    showPreview: "显示预览",
    attachPhoto: "添加照片",
    exporting: "正在导出...",
    apiProvider: "API 供应商",
    baseUrl: "基础 URL",
    apiKey: "API 密钥",
    model: "模型",
    fetchModels: "正在获取模型...",
    noModels: "未找到模型",
    refresh: "刷新",
    apiKeyPlaceholder: "API 密钥",
    optionalLocal: "(本地模式可选)",
    enterKeyToLoad: "输入 API 密钥以加载模型",
    modelNamePlaceholder: "模型名称",
    selectModel: "— 选择模型 —",
    restore: "还原",
    maximize: "最大化",
    minimize: "最小化",
    errorLabel: "错误"
  }
};

export const INITIAL_RESUME_DATA: ResumeData = {
  layout: {
    type: "two_column",
    accent_color: "#1E1E1E",
    background_color: "#FFFFFF",
    border_style: "none",
    font_family: "Inter",
    photo_placement: "sidebar_top_circle",
    skills_style: "progress_bars",
    spacing: "compact",
    section_order: {
      sidebar: ["skills", "languages", "contact"],
      main: ["summary", "experience", "education"]
    }
  },
  content: {
    personal: {
      name: "NGUYỄN BÌNH",
      title: "Senior Software Engineer",
      email: "ngocbinht41@gmail.com",
      phone: "+84 90 123 4567",
      location: "Hà Nội, Việt Nam",
      linkedin: "linkedin.com/in/nguyenbinh",
      photo_url: "https://picsum.photos/seed/avatar/200/200"
    },
    sections: [
      {
        id: "summary",
        title: "Tóm tắt chuyên môn",
        type: "text",
        items: [
          {
            description: "Kỹ sư phần mềm với hơn 8 năm kinh nghiệm trong việc xây dựng các ứng dụng web quy mô lớn. Chuyên gia về React, Node.js và kiến trúc hệ thống đám mây. Đam mê tạo ra các sản phẩm có trải nghiệm người dùng tuyệt vời và hiệu năng cao."
          }
        ]
      },
      {
        id: "experience",
        title: "Kinh nghiệm làm việc",
        type: "experience",
        items: [
          {
            title: "Senior Fullstack Developer",
            subtitle: "Tech Solutions Corp",
            location: "Hà Nội",
            period: "2020 - Hiện tại",
            bullets: [
              "Dẫn dắt đội ngũ 5 người phát triển hệ thống quản lý kho vận quy mô lớn.",
              "Tối ưu hóa hiệu năng ứng dụng React, giảm 40% thời gian tải trang.",
              "Triển khai kiến trúc microservices với Docker và Kubernetes."
            ]
          },
          {
            title: "Web Developer",
            subtitle: "Creative Agency",
            location: "Hà Nội",
            period: "2017 - 2020",
            bullets: [
              "Phát triển hơn 50 dự án website cho khách hàng trong và ngoài nước.",
              "Xây dựng hệ thống CMS tùy chỉnh giúp khách hàng quản lý nội dung dễ dàng.",
              "Hợp tác chặt chẽ với đội ngũ thiết kế để đảm bảo tính thẩm mỹ và khả năng sử dụng."
            ]
          }
        ]
      },
      {
        id: "education",
        title: "Học vấn",
        type: "education",
        items: [
          {
            title: "Cử nhân Công nghệ thông tin",
            subtitle: "Đại học Bách Khoa Hà Nội",
            period: "2013 - 2017",
            description: "Tốt nghiệp loại Giỏi. Chuyên ngành Hệ thống thông tin."
          }
        ]
      },
      {
        id: "skills",
        title: "Kỹ năng",
        type: "skills",
        items: [
          { title: "React / Next.js", level: 95 },
          { title: "Node.js / Express", level: 90 },
          { title: "TypeScript", level: 85 },
          { title: "PostgreSQL / MongoDB", level: 80 },
          { title: "AWS / Google Cloud", level: 75 }
        ]
      },
      {
        id: "languages",
        title: "Ngoại ngữ",
        type: "list",
        items: [
          { title: "Tiếng Việt (Bản ngữ)" },
          { title: "Tiếng Anh (IELTS 7.5)" }
        ]
      }
    ]
  },
  coach_message: "Chào mừng bạn! Tôi đã tạo một bản nháp CV dựa trên thông tin của bạn. Bạn có thể yêu cầu tôi thay đổi màu sắc, bố cục hoặc thêm bớt các phần nội dung khác."
};
