export const PROVIDERS = [
  { id: 'gemini',     name: 'Google Gemini',  base_url: '',                                  needs_key: true,  key_placeholder: 'AIza...',   color: '#4285F4', initials: 'G',  domain: 'google.com'       },
  { id: 'openai',     name: 'OpenAI',          base_url: 'https://api.openai.com/v1',         needs_key: true,  key_placeholder: 'sk-...',    color: '#10A37F', initials: 'AI', domain: 'openai.com'       },
  { id: 'groq',       name: 'Groq',            base_url: 'https://api.groq.com/openai/v1',    needs_key: true,  key_placeholder: 'gsk_...',   color: '#F55036', initials: 'GQ', domain: 'groq.com'         },
  { id: 'openrouter', name: 'OpenRouter',      base_url: 'https://openrouter.ai/api/v1',      needs_key: true,  key_placeholder: 'sk-or-...', color: '#6467F2', initials: 'OR', domain: 'openrouter.ai'    },
  { id: 'mistral',    name: 'Mistral',         base_url: 'https://api.mistral.ai/v1',         needs_key: true,  key_placeholder: 'API key',   color: '#FF7000', initials: 'M',  domain: 'mistral.ai'       },
  { id: 'deepseek',   name: 'DeepSeek',        base_url: 'https://api.deepseek.com/v1',       needs_key: true,  key_placeholder: 'sk-...',    color: '#4D6BFE', initials: 'DS', domain: 'deepseek.com'     },
  { id: 'together',   name: 'Together AI',     base_url: 'https://api.together.xyz/v1',       needs_key: true,  key_placeholder: 'API key',   color: '#8B5CF6', initials: 'T',  domain: 'together.ai'      },
  { id: 'ollama',     name: 'Ollama (local)',  base_url: 'http://localhost:11434/v1',          needs_key: false, local: true,                  color: '#1C1C1E', initials: 'OL', domain: 'ollama.com'       },
  { id: 'lmstudio',   name: 'LM Studio',       base_url: 'http://localhost:1234/v1',           needs_key: false, local: true,                  color: '#7C3AED', initials: 'LM', domain: 'lmstudio.ai'      },
  { id: 'custom',     name: 'Custom / Other',  base_url: '',                                  needs_key: false,                               color: '#71717A', initials: '?',  domain: null               },
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    welcome: "Hi! I'm SlothCV. I can help you design a stunning resume. What's your name and what role are you looking for?",
    newChat: "New Chat",
    recentChats: "Recent Chats",
    noSessions: "No recent chats",
    settings: "Settings",
    preview: "Preview",
    exportPdf: "Export PDF",
    exporting: "Exporting...",
    clearData: "Clear All Data",
    clearDataConfirm: "Are you sure? This will delete all your sessions and settings.",
    cancel: "Cancel",
    save: "Save",
    saved: "Saved!",
    saving: "Saving...",
    send: "Send",
    placeholder: "Type a message...",
    resumeDraft: "Resume Design",
    clickToView: "Click to view",
    artifactDesc: "The AI has updated your resume design.",
    open: "Open",
    showPreview: "Show Preview",
    hidePreview: "Hide Preview",
    apiProvider: "AI Provider",
    apiKey: "API Key",
    apiKeyPlaceholder: "Enter your API key",
    baseUrl: "Base URL",
    model: "Model",
    selectModel: "Select a model",
    fetchModels: "Fetching models...",
    refresh: "Refresh",
    optionalLocal: "Optional for local",
    modelNamePlaceholder: "e.g. gpt-4o, gemini-1.5-pro",
    enterKeyToLoad: "Enter API key to load models",
    setupAi: "Setup AI",
    noResumeData: "No resume data yet. Start chatting to build one!",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close: "Close",
    attachPhoto: "Attach Photo",
    clearDataError: "Failed to clear data",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
  },
  vi: {
    welcome: "Chào bạn! Tôi là SlothCV. Tôi có thể giúp bạn thiết kế một bản CV ấn tượng. Bạn tên là gì và đang tìm kiếm vị trí nào?",
    newChat: "Cuộc hội thoại mới",
    recentChats: "Gần đây",
    noSessions: "Chưa có hội thoại nào",
    settings: "Cài đặt",
    preview: "Xem trước",
    exportPdf: "Xuất PDF",
    exporting: "Đang xuất...",
    clearData: "Xóa toàn bộ dữ liệu",
    clearDataConfirm: "Bạn có chắc chắn không? Hành động này sẽ xóa tất cả các phiên chat và cài đặt của bạn.",
    cancel: "Hủy",
    save: "Lưu",
    saved: "Đã lưu!",
    saving: "Đang lưu...",
    send: "Gửi",
    placeholder: "Nhập tin nhắn...",
    resumeDraft: "Bản thiết kế CV",
    clickToView: "Nhấn để xem",
    artifactDesc: "AI vừa cập nhật lại thiết kế CV của bạn.",
    open: "Mở",
    showPreview: "Hiện xem trước",
    hidePreview: "Ẩn xem trước",
    apiProvider: "Nhà cung cấp AI",
    apiKey: "API Key",
    apiKeyPlaceholder: "Nhập mã API của bạn",
    baseUrl: "Địa chỉ máy chủ (URL)",
    model: "Mô hình (Model)",
    selectModel: "Chọn một mô hình",
    fetchModels: "Đang tải danh sách...",
    refresh: "Làm mới",
    optionalLocal: "Không bắt buộc với local",
    modelNamePlaceholder: "VD: gpt-4o, gemini-1.5-pro",
    enterKeyToLoad: "Nhập key để tải danh sách",
    setupAi: "Cài đặt AI",
    noResumeData: "Chưa có dữ liệu CV. Hãy chat để bắt đầu tạo nhé!",
    minimize: "Thu nhỏ",
    maximize: "Phóng to",
    restore: "Khôi phục",
    close: "Đóng",
    attachPhoto: "Thêm ảnh chân dung",
    clearDataError: "Lỗi khi xóa dữ liệu",
    lightMode: "Chế độ sáng",
    darkMode: "Chế độ tối",
  }
};
